<a href="https://colab.research.google.com/github/pavansaikrishna78/Create-Blog/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Loading Library

In [ ]:
import numpy as np

creating numpy array

In [ ]:
# array from a python list
list1=[2,4,6,8,10]
arr1=np.array(list1)

In [ ]:
arr1

array([ 2,  4,  6,  8, 10])

In [ ]:
list1

[2, 4, 6, 8, 10]

In [ ]:
type(list1)

list

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
list1+1

TypeError: ignored

In [ ]:
arr1+1

array([ 3,  5,  7,  9, 11])

In [ ]:
list2=[[9,0,4,6],[4,6,2,1]]

In [ ]:
arr2=np.array(list2)

In [ ]:
arr2

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

In [ ]:
arr3=l2.astype('int')

In [ ]:
arr3

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

In [ ]:
arr4=np.array(arr3,dtype='bool')

In [ ]:
arr4

array([[ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
list2

[[9, 0, 4, 6], [4, 6, 2, 1]]

In [ ]:
arr5=np.array([2,5,2.0,'y'],dtype='object')

In [ ]:
arr5

array([2, 5, 2.0, 'y'], dtype=object)

In [ ]:
list3=arr5.tolist()

In [ ]:
list3

[2, 5, 2.0, 'y']

In [ ]:
type(arr5)

numpy.ndarray

In [ ]:
type(list3)

list

2 Array Dimensions

In [ ]:
arr2=[[9.,0.,4.,6.],[4.,6.,2.,1.]]

In [ ]:
arr2

[[9.0, 0.0, 6.0], [4.0, 6.0, 2.0, 1.0]]

In [ ]:
arr2.shape

(2, 4)

In [ ]:
arr2.size

8

In [ ]:
arr2.ndim

2

Reversing Rows and Coloumns

In [ ]:
arr2

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

In [ ]:
arr2[::-1,::-1]

array([[1, 2, 6, 4],
       [6, 4, 0, 9]])

In [ ]:
arr2[::-1]

array([[4, 6, 2, 1],
       [9, 0, 4, 6]])

4 specific element extraction

In [ ]:
arr2

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

In [ ]:
arr2[0,:]

array([9, 0, 4, 6])

In [ ]:
arr2[:1,:]

array([[9, 0, 4, 6]])

In [ ]:
arr2[:2,:]

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

In [ ]:
arr2[:-1,:]

array([[9, 0, 4, 6]])

In [ ]:
arr2[:,-1]

array([6, 1])

In [ ]:
arr2[:,1:3]

array([[0, 4],
       [6, 2]])

5 basic statistics

In [ ]:
arr2

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

In [ ]:
arr2.min()

0

In [ ]:
arr2.max()

9

In [ ]:
arr2.sum()

32

In [ ]:
arr2.mean()

4.0

In [ ]:
np.median(arr2)

4.0

In [ ]:
np.average(arr2)

4.0

In [ ]:
np.var(arr2)

7.75

Reshaping and Flattening

In [ ]:
arr2

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

In [ ]:
arr2.shape

(2, 4)

In [ ]:
arr2.reshape(4,2)

array([[9, 0],
       [4, 6],
       [4, 6],
       [2, 1]])

In [ ]:
arr2.reshape(1,8)

array([[9, 0, 4, 6, 4, 6, 2, 1]])

In [ ]:
arr2.reshape(8,1)

array([[9],
       [0],
       [4],
       [6],
       [4],
       [6],
       [2],
       [1]])

In [ ]:
f1=arr2.flatten()

In [ ]:
f1

array([9, 0, 4, 6, 4, 6, 2, 1])

In [ ]:
arr2.ndim

2

In [ ]:
f1.ndim

1

Reshaping and flattening

In [ ]:
arr2

array([[9, 0, 4, 6],
       [4, 6, 2, 1]])

In [ ]:
arr2.shape

(2, 4)

Creating Random Array Sequence

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(10,0)

array([], dtype=int64)

In [ ]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
np.linspace(1,10,13)

array([ 1.  ,  1.75,  2.5 ,  3.25,  4.  ,  4.75,  5.5 ,  6.25,  7.  ,
        7.75,  8.5 ,  9.25, 10.  ])

In [ ]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

Unique Items and count

In [ ]:
arr=[[1,2,3,4,5,6],[4,4,1,7,4,5]]

In [ ]:
arr

[[1, 2, 3, 4, 5, 6], [4, 4, 1, 7, 4, 5]]

In [ ]:
u_val,count = np.unique(arr,return_counts=True)

In [ ]:
u_val

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
count

array([2, 1, 1, 4, 2, 1, 1])

Loading library

In [ ]:
import pandas as pd
import numpy as np

Create Data Frame

In [ ]:
data={
    'roll_no':[3,2,7,11],
    'ppr_id' :[34,21,10,11],
    'marks'  :[30,23,17,27]
}

In [ ]:
df1 = pd.DataFrame

In [ ]:
data

{'marks': [30, 23, 17, 27],
 'ppr_id': [34, 21, 10, 11],
 'roll_no': [3, 2, 7, 11]}

In [ ]:
df1

pandas.core.frame.DataFrame

2 setting index

In [ ]:
df2 = pd.DataFrame(data,index=['ab','ef','xy','uv'])

In [ ]:
df2

roll_no  ppr_id  marks
ab        3      34     30
ef        2      21     23
xy        7      10     17
uv       11      11     27

extracting info

In [ ]:
df2.loc['xy']

roll_no     7
ppr_id     10
marks      17
Name: xy, dtype: int64

In [ ]:
df2.iloc[:,-1]

ab    30
ef    23
xy    17
uv    27
Name: marks, dtype: int64

In [ ]:
df2.iloc[0:2,2:3]

marks
ab     30
ef     23

Working on csv

1 Loading Data

In [ ]:
import pandas as pd
df = pd.read_csv('/content/sample_data/iris.csv')

In [ ]:
df.head(10)

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


Data Description

In [ ]:
df.describe()

sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
df['sepal.width'][:5]

0    3.5
1    3.0
2    3.2
3    3.1
4    3.6
Name: sepal.width, dtype: float64

In [ ]:
df[['sepal.width']][:5]

sepal.width
0          3.5
1          3.0
2          3.2
3          3.1
4          3.6

In [ ]:
df[['sepal.width','petal.width']].head()

sepal.width  petal.width
0          3.5          0.2
1          3.0          0.2
2          3.2          0.2
3          3.1          0.2
4          3.6          0.2

In [ ]:
df.iloc[:10,[1,3]]

sepal.width  petal.width
0          3.5          0.2
1          3.0          0.2
2          3.2          0.2
3          3.1          0.2
4          3.6          0.2
5          3.9          0.4
6          3.4          0.3
7          3.4          0.2
8          2.9          0.2
9          3.1          0.1

In [ ]:
data = {
    'roll_no' :[3,2,7,11],
    'ppr_id'  :[34,21,10,11],
     'marks'  :[np.nan,23,17,27]
}

In [ ]:
df1=pd.DataFrame(data)

NULL

In [ ]:
df1.isnull()

In [ ]:
df1

roll_no  ppr_id  marks
0        3      34    NaN
1        2      21   23.0
2        7      10   17.0
3       11      11   27.0

In [ ]:
df1.isnull().sum()

roll_no    0
ppr_id     0
marks      1
dtype: int64

In [ ]:
df2=df1.fillna(1)

In [ ]:
df2

roll_no  ppr_id  marks
0        3      34    1.0
1        2      21   23.0
2        7      10   17.0
3       11      11   27.0